@startuml
'https://plantuml.com/class-diagram

package chiquileague {
    package model {

        class Engine implements .chiquileague.observer.Subject, .chiquileague.mvc.Model {
            Season season
            GameInfo gameInfo

            connectDatabase()
            newGame(String newGameName, Team selectedTeam)
            initializeCompetitions()
            loadGame(Path saveFile)
            nextDay()
            saveGameAndQuit()
            quitGame()

            registerObserver(Observer observer)
            removeObserver(Observer observer)
            notifyObservers()
        }
        Engine --> Season
        Engine --> GameInfo

        class Season {
            startDate: LocalDate
            endDate: LocalDate
            Season(startDate: LocalDate)
            getFixtureByTeam(team: Team)
            getFixtureByCompetition(league: League)
        }

        class GameInfo {
            id: Integer
            name: String
            clubID: Integer
            time: Date
            selectedTeam: Team
        }
        GameInfo::selectedTeam -> Team

        abstract Competition {
            id: Integer
            name: String
            competitionFormat: String
        }

        class League extends Competition {
            countryID: Integer
            leagueRank: Integer
        }

        class NationalCup extends Competition {
            countryID: Integer
        }

        class InternationalCup extends Competition {
            countriesIDs: List<Integer>
        }

        class Country {
            id: Integer
            String: name
        }

        class Match {
            id: Integer
            date: Date
            homeGoals: Integer
            awayGoals: Integer
            homeClubID: Integer
            awayClubID: Integer
            stadiumID: Integer
            competitionID: Integer
            matchday: Integer
        }

        class Player {
            id: int
            name: String
            birthDate: Date
            age: int
            nationality: String

            foot: String
            height: float
            passing: int
            shooting: int
            dribbling: int
            tackling: int
            pace: int
            stamina: int
            vision: int
            positioning: int
            decisionMaking: int
            strength: int

            positions: List<Position>

            attrID: int
            clubID: int
            contractID: int
            youthAcademyID: Integer
        }

        enum Position {
            PO
            DFC
            DFI
            DFD
            MCD
            MC
            MI
            MD
            DC
            MCO
            MP
            EI
            ED
        }

        class Stadium {
            id: Integer
            name: String
            capacity: Integer
            clubID: Integer
        }

        class Stats {
            competitionID: Integer
            ClubID: Integer
            points: Integer
            matchesPlayed: Integer
            wins: Integer
            draws: Integer
            losses: Integer
            goalsFor: Integer
            goalsAgainst: Integer
            goalDifference: Integer
        }

        class Team {
            id: Integer
            name: String
            leagueID: Integer
        }
    }

    package fixture {
        interface FixtureGenerator {
            generate(competitionID: int, startDate: LocalDate)
        }

        class DoubleRoundRobinGenerator implements FixtureGenerator {
            generate(competitionID: int, startDate: LocalDate)
        }

        class DoubleRoundRobinPlayoffsGenerator implements FixtureGenerator {
            generate(competitionID: int, startDate: LocalDate)
        }

        class GroupKnockoutGenerator implements FixtureGenerator {
            generate(competitionID: int, startDate: LocalDate)
        }

        class KnockoutGenerator implements FixtureGenerator {
            generate(competitionID: int, startDate: LocalDate)
        }

        class FixtureFactory {
            getGenerator(type: String)
        }

    }

    package dao {
        class CompetitionDAO {
            fetchLeague(id: Integer)
            fetchLeague(name: String)
            fetchNationalCup(id: Integer)
            fetchNationalCup(name: String)
            fetchInternationalCup(id: Integer)
            fetchInternationalCup(name: String)
            fetchAll(): List<Competition>
            getTeamsByLeague(league: League)
        }

        class CountryDAO {
            fetch(id: Integer)
            fetch(name: String)
            getLeagues(country: Country)
        }

        class GameDAO {
            fetch(id: Integer): GameInfo
            fetch(name: String): GameInfo
        }

        class MatchDAO {
            fetch(date: Date, stadiumID: Integer)
            fetch(id: Integer)
            insert(match: Match)
            fetchMatchesByTeam(team: Team)
            fetchMatchesByCompetition(competition: Competition)
            fetchMatchesOfTheDay(date: Date)
        }

        class PlayerDAO {
            fetch(id: Integer)
            fetch(name: String)
        }

        class StadiumDAO {
            fetch(id: Integer)
            fetch(name: String)
            fetchByClubID(clubID: Integer)
        }

        class StatsDAO {
            fetch(competitionID: Integer, clubID: Integer)
        }

        class TeamDAO {
            fetch(id: Integer)
            fetch(name: String)
            getPlayers(team: Team)
        }

        class Database {
            DB_RESOURCE_PATH: String
            connection: Connection

            connect()
            getConnection()
            close()
            connectTo(dbPath: Path)
            fetchCountries()
            createGame(name: String, clubID: Integer)
            saveGame(gameInfo: GameInfo)
        }
    }

    package mvc {
        interface Model {
            connectDatabase()
            newGame(String newGameName, Team selectedTeam)
            initializeCompetitions()
            loadGame(Path saveFile)
            nextDay()
            saveGameAndQuit()
            quitGame()
        }

        interface View {
            mainMenu()
            gameMenu()
            errorMessage(String msg)
            print(String msg)
            showList(List<?> list)
            showMatchesOfTheDay()
            showSquad()
            showCalendar()
        }

        interface Controller {
            startGameLoop()
            newGame()
            loadGame()
        }
    }

    package observer {
        interface Subject {
            registerObserver(Observer observer)
            removeObserver(Observer observer)
            notifyObservers()
        }

        interface Observer {
            update()
        }
    }

    package Controller {
        class MVPController implements .chiquileague.mvc.Controller {
            Model model
            View view

            MVPController(Model model)
            startGameLoop()
            newGame()
            loadGame()
        }
        MVPController --- Model
        MVPController --- View
    }

    package View {
        class ConsoleView implements .chiquileague.mvc.View, .chiquileague.observer.Observer {
            GameInfo gameInfo

            mainMenu()
            gameMenu()
            errorMessage(String msg)
            print(String msg)
            showList(List<?> list)
            showMatchesOfTheDay()
            showSquad()
            showCalendar()

            update()
        }
    }

    package app {
        class App {
        }

        class MVP {
        }
    }
}

@enduml